### ISSUE TITLE
Weird problem with MessageBoxA

### ISSUE THREAD

**Issue by Portobenne** [JustasMasiulis/lazy_importer#45]
Hi @JustasMasiulis i encountered a weird issue when I tried out your project.

When I try this, cache doesnt return:

```cpp
//  cache doesent return, msg box doesent
LI_FN(MessageBoxA).in(LI_MODULE("user32.dll").cached())(nullptr, "Im hidden in imports", "Lazy Importer Test", MB_OK);
```
However, when I add a second MessageBoxA under it both work all of the sudden:

```cpp
//  cache returns, both msg boxes work
LI_FN(MessageBoxA).in(LI_MODULE("user32.dll").cached())(nullptr, "Im hidden in imports", "Lazy Importer Test", MB_OK);
MessageBoxA(nullptr, "Im hidden in imports", "Lazy Importer Test", MB_OK); // ofc in imports
```
I tried other winapi calls and the same problem occured, unless with OutputDebugMessage.
I just keep having the same issue, I tried to use get() but an exception is thrown that base is nullptr (ln 355):

```cpp
//  crashed because of nullptr base
LI_FN(MessageBoxA).get()(nullptr, "Im hidden in imports", "Lazy Importer Test", MB_OK);
```
I dont understand what I am doing wrong.

**Comment by Mecanik** [comment]
Take a step back and **try to understand** what this library does and how it works. 

First of all, MessageBoxA is coming from User32.dll. With that being said, if User32.dll is **not loaded into your process**, there is no MessageBoxA.

**This library does not load DLL's** (imports) for you automatically (yet). What that means is that you need to have User23.dll marked as import in your executable or **import it yourself**.

This is the reason why your second example works where you add a plain MessageBoxA is because the compiler **adds User32.dll as an import**.

So in order to quickly solve your problem (if you don't want to mark User32 as an import in your executable/dll), simply add:

`LoadLibrary("User32.dll");`

Do this **before calling** any lazy_importer definitons.

**Comment by Portobenne** [comment]
@Mecanik Ah okay, I thought this version is doing it automatically, my fault for not checking the src. Thank you for the quick answer :)

**Comment by Portobenne** [comment]
@JustasMasiulis Thank you for the clarification. I have one more question, why does this library rely on Loadlibrary. Why cant I use the base address, and then find the export table?

**Comment by JustasMasiulis** [comment]
> @JustasMasiulis Thank you for the clarification. I have one more question, why does this library rely on Loadlibrary. Why cant I use the base address, and then find the export table?

There is no base address, since the DLL is not loaded. This library does not load DLLs for you. If you want to use `SomeLibrary!SomeFunction` you need to load `SomeLibrary` in any way you want (LoadLibraryA, LdrLoadLibrary, manual mapping) and then either pass its base to the `.in` function or add it into the loaded library list in PEB if it's not done for you in the case of manual mapping.

The reason that your code started working when you added the non lazy imported `MessageBoxA` is because it got added to your executables import table, which in turn loaded library this function resides in during process initialization.

**Comment by Portobenne** [comment]
@JustasMasiulis  yeah I know that was my issue, I was just wondering because I used a similar technique before but I used the base address. Okay im going to try manual mapping then because I rather not use Loadlibrary. Thanks for everything!
